In [1]:
from bs4 import BeautifulSoup
import requests
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import time

from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service

In [14]:
#1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
# You need to find following details:A) Rank B) Name C) Artist D) Upload date E) Views

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
url="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos" 
driver.get(url)

#maximize the chrome window
driver.maximize_window()

In [56]:
# Empty lists
Rank=[]
Name=[]
Artist=[]
Views=[]
Upload_date=[]

#scrapping the data for empty lits
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
    Rank.append(i.text)
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
    Name.append(i.text)
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]"):
    Artist.append(i.text)
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
    Views.append(i.text)
for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]"):
    Upload_date.append(i.text)
    
#DataFrame
most_viewed_videos=pd.DataFrame({'Rank':Rank,'Name':Name,'Artist':Artist,'Views':Views,'Upload date':Upload_date})
most_viewed_videos

,Rank,Name,Artist,Views,Upload date
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,10.92,"June 17, 2016"
1,2.,"""Despacito""[6]",Luis Fonsi,7.90,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,6.39,"October 8, 2016"
3,4.,"""Shape of You""[13]",Ed Sheeran,5.76,"January 30, 2017"
4,5.,"""See You Again""[15]",Wiz Khalifa,5.56,"April 6, 2015"
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,5.50,"May 2, 2018"
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,4.71,"March 6, 2014"
7,8.,"""Uptown Funk""[22]",Mark Ronson,4.62,"November 19, 2014"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,4.59,"February 27, 2018"
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,4.50,"January 31, 2012"
10,11.,"""Gangnam Style""[25]",Psy,4.47,"July 15, 2012"
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,4.18,"May 24, 2018"
12,13.,"""Dame Tu Cosita""[31]",El Chombo,3.97,"April 5, 2018"
13,14.,"""Sugar""[32]",Maroon 5,3.72,"January 14, 2015"
14,15.,"""Roar""[33]",Katy Perry,3.61,"September 5, 2013"
15,16.,"""Counting Stars""[34]",OneRepublic,3.60,"May 31, 2013"
16,17.,"""Sorry""[35]",Justin Bieber,3.56,"October 22, 2015"
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,3.47,"October 7, 2014"
18,19.,"""Axel F""[37]",Crazy Frog,3.42,"June 16, 2009"
19,20.,"""Girls Like You""[38]",Maroon 5,3.31,"May 31, 2018"
20,21.,"""Faded""[39]",Alan Walker,3.30,"December 3, 2015"
21,22.,"""Dark Horse""[40]",Katy Perry,3.30,"February 20, 2014"
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,3.28,"June 25, 2018"
23,24.,"""Let Her Go""[42]",Passenger,3.26,"July 25, 2012"
24,25.,"""Bailando""[43]",Enrique Iglesias,3.23,"April 11, 2014"
25,26.,"""Lean On""[44]",Major Lazer,3.23,"March 22, 2015"
26,27.,"""Perfect""[45]",Ed Sheeran,3.20,"November 9, 2017"
27,28.,"""Shake It Off""[46]",Taylor Swift,3.19,"August 18, 2014"
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,3.18,"June 4, 2010"
29,30.,"""Mi Gente""[48]",J Balvin,3.10,"June 29, 2017"

In [58]:
driver.close()

In [67]:
#2. Scrape the details team India’s international fixtures from bcci.tv.Url = https://www.bcci.tv/.You need to find following details:
#A) Match title (I.e. 1st ODI) B) Series C) Place D) Date E) Time Note: - From bcci.tv home page you have reach to the international fixture page through code.

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="https://www.bcci.tv/" 
driver.get(url)

#maximize the chrome window
driver.maximize_window() 

#Getting India’s international fixtures
internationl=driver.find_element_by_xpath('//ul[@class="nav navbar-nav  align-items-center"]/li[2]/a').get_attribute('href')
driver.get(internationl)

In [88]:
Match_title=[]
Series=[]
Place=[]
Date=[]
Time_Note=[]

for i in driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]'):
    Match_title.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="ng-binding"]'):
    Series.append(i.text)
for i in driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]/span[2]'):
    Place.append(i.text)
for i in driver.find_elements_by_xpath('//h5[@class="ng-binding"]'):
    Date.append(i.text)
for i in driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]'):
    Time_Note.append(i.text)
    
#DataFrame
international_fixtures=pd.DataFrame({'Match_title':Match_title,'Series':Series,'Place':Place,'Date':Date,'Time_Note':Time_Note})
international_fixtures

,Match_title,Series,Place,Date,Time_Note
0,3rd T20I -,INDIA TOUR OF ENGLAND T20 SERIES 2022,"Trent Bridge,",10 JUL 2022,7:00 PM IST
1,1st ODI -,INDIA TOUR OF ENGLAND ODI SERIES 2022,"Kennington Oval,",12 JUL 2022,5:30 PM IST
2,2nd ODI -,INDIA TOUR OF ENGLAND ODI SERIES 2022,"Lord's Cricket Ground,",14 JUL 2022,5:30 PM IST
3,3rd ODI -,INDIA TOUR OF ENGLAND ODI SERIES 2022,"Old Trafford,",17 JUL 2022,3:30 PM IST
4,1st ODI -,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval,",22 JUL 2022,7:00 PM IST
5,2nd ODI -,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval,",24 JUL 2022,7:00 PM IST
6,3rd ODI -,INDIA TOUR OF WEST INDIES ODI SERIES 2022,"Queens Park Oval,",27 JUL 2022,7:00 PM IST

In [89]:
driver.close()

In [3]:
# 3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/ You need to find following details:
 #A) Name B) Description Note: - From guru99 home page you have to reach to selenium exception handling page through code
    
#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="https://www.guru99.com/" 
driver.get(url)

#maximize the chrome window
driver.maximize_window() 

# Search selenium exception handling
a=driver.find_element_by_id("gsc-i-id1")
a.send_keys("selenium exception handling")

#click on search 
click=driver.find_element_by_xpath("//button[@class='gsc-search-button gsc-search-button-v2']").click()

# Getting selenium exception handling page
search=driver.find_element_by_xpath("//div[@class='gs-title']/a").get_attribute('href')
driver.get(search)

In [64]:
# Empty Lists
Exception_name=[]
Description=[]

# Scraping data
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]"):
    Exception_name.append(i.text)
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]"):
    Description.append(i.text)

Lits=pd.DataFrame({'Exception name':Exception_name,'Description':Description})
Lits

,Exception name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [ ]:
driver.close()

In [2]:
# 4. Scrape the details of State-wise GDP of India from statisticstime.com.Url = http://statisticstimes.com/ You have to find following details:
#A) Rank B) State C) GSDP(18-19) D) GSDP(17-18) E) Share(2017) F) GDP($ billion) Note: - From statisticstimes home page you have to reach to economy page through code.

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="http://statisticstimes.com/" 
driver.get(url)

#maximize the chrome window
driver.maximize_window() 

# Getting Economy page
Economy=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button").click()
india=driver.find_element_by_xpath("//div[@class='dropdown-content']/a[3]").click()

#Click on GDP of India
try:
    state=driver.find_element_by_xpath('//a[@href="india/indian-states-gdp.php"]').click()
except:
    s=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()

In [24]:
url = driver.current_url
url

'https://www.statisticstimes.com/economy/india/indian-states-gdp.php'

In [77]:
page=requests.get(url) #send get request to the webpage server to get the source code of the page
print(page)

print('-------------------------------')

bs=BeautifulSoup(page.content)
#getting the table by using pandas readhtml method
Table=bs.find_all('table')

df = pd.read_html(str(Table))[1]
df

<Response [200]>
-------------------------------

    Rank                      State GSDP (Cr INR at Current prices)            \
    Rank                      State                           19-20     18-19
0    1.0                Maharashtra                               -   2632792
1    2.0                 Tamil Nadu                         1845853   1630208
2    3.0              Uttar Pradesh                         1687818   1584764
3    4.0                    Gujarat                               -   1502899
4    5.0                  Karnataka                         1631977   1493127
5    6.0                West Bengal                         1253832   1089898
6    7.0                  Rajasthan                         1020989    942586
7    8.0             Andhra Pradesh                          972782    862957
8    9.0                  Telangana                          969604    861031
9   10.0             Madhya Pradesh                          906672    809592
10  11.0                     Kerala                               -    781653
11  12.0                      Delhi                          856112    774870
12  13.0                    Haryana                          831610    734163
13  14.0                      Bihar                          611804    530363
14  15.0                     Punjab                          574760    526376
15  16.0                     Odisha                          521275    487805
16  17.0                      Assam                               -    315881
17  18.0               Chhattisgarh                          329180    304063
18  19.0                  Jharkhand                          328598    297204
19  20.0                Uttarakhand                               -    245895
20  21.0            Jammu & Kashmir                               -    155956
21  22.0           Himachal Pradesh                          165472    153845
22  23.0                        Goa                           80449     73170
23  24.0                    Tripura                           55984     49845
24  25.0                 Chandigarh                               -     42114
25  26.0                 Puducherry                           38253     34433
26  27.0                  Meghalaya                           36572     33481
27  28.0                     Sikkim                           32496     28723
28  29.0                    Manipur                           31790     27870
29  30.0                   Nagaland                               -     27283
30  31.0          Arunachal Pradesh                               -     24603
31  32.0                    Mizoram                           26503     22287
32  33.0  Andaman & Nicobar Islands                               -         -
33   NaN                      India                        20351013  18886957

     Share GDP ($billion) GSDP (Cr INR at 2011-12 prices)
     18-19           2019                           19-20     18-19
0   13.94%        399.921                               -   2039074
1    8.63%        247.629                         1312929   1215307
2    8.39%        240.726                         1166817   1123982
3    7.96%        228.290                               -   1186379
4    7.91%        226.806                         1156039   1091077
5    5.77%        165.556                          793223    739525
6    4.99%        143.179                          711627    677428
7    4.57%        131.083                          672018    621301
8    4.56%        130.791                          663258    612828
9    4.29%        122.977                          561801    522009
10   4.14%        118.733                               -    559412
11   4.10%        117.703                          634408    590569
12   3.89%        111.519                          572240    531085
13   2.81%         80.562                          414977    375651
14   2.79%         79.957                          418868    397669
15   2.58%         74.098                          396499    376877
16   1.67%         47.982                               -    234048
17   1.61%         46.187                          243477    231182
18   1.57%         45.145                          240036    224986
19   1.30%         37.351                               -    193273
20   0.83%         23.690                               -    112755
21   0.81%         23.369                          124403    117851
22   0.39%         11.115                           63408     57787
23   0.26%          7.571                           40583     36963
24   0.22%          6.397                               -     31192
25   0.18%          5.230                           25093     23013
26   0.18%          5.086                           26695     24682
27   0.15%          4.363                           20017     18722
28   0.15%          4.233                           20673     19300
29   0.14%          4.144                               -     17647
30   0.13%          3.737                               -     16676
31   0.12%          3.385                           18797     16478
32       -              -                               -         -
33     NaN           2869                        14569268  14003316

In [ ]:
driver.close()

In [15]:
# 5. Scrape the details of trending repositories on Github.com. Url = https://github.com/ You have to find the following details:
#A) Repository title B) Repository description C) Contributors count D) Language used

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="https://github.com/" 
driver.get(url)
delay=30
WebDriverWait(driver,delay).until(EC.presence_of_element_located((By.XPATH,('//a[@href="/trending"]'))))

#maximize the chrome window
driver.maximize_window()

In [ ]:
from selenium.common.exceptions import ElementNotInteractableException

try:
    driver.find_element_by_xpath('//a[@href="/trending"]').click()
except ElementNotInteractableException as e:
    print('Exception Raised', e)
    a=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
    driver.get(a.get_attribute('href'))

In [23]:
url=driver.current_url
url

'https://github.com/trending'

In [31]:
#Empty lits
Repository_title=[]
Repository_description=[]
Contributors_count=[]
Language_used=[]

#Scraping data
for i in driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]/a'):
    Repository_title.append(i.text)
for i in driver.find_elements_by_xpath('//p[@class="col-9 color-fg-muted my-1 pr-4"]'):
    Repository_description.append(i.text)
for i in driver.find_elements_by_xpath('//a[@class="Link--muted d-inline-block mr-3"]'):
    Contributors_count.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="d-inline-block ml-0 mr-3"]'):
    Language_used.append(i.text)
    
# Creating DataFrame
Github=pd.DataFrame({'Repository title':Repository_title[:21],'Repository description':Repository_description[:21],'Contributors count':Contributors_count[:21],'Language used':Language_used[:21]})
Github

,Repository title,Repository description,Contributors count,Language used
0,pocketbase / pocketbase,Open Source realtime backend in 1 file,"3,843",Go
1,Jarred-Sumner / bun,"Incredibly fast JavaScript runtime, bundler, t...",92,Zig
2,codecrafters-io / build-your-own-x,Master programming by recreating your favorite...,"19,547",Python
3,sindresorhus / awesome,😎 Awesome lists about all kinds of interesting...,337,Python
4,facundoolano / software-papers,📚 A curated list of papers for Software Engineers,"148,954",C
5,public-apis / public-apis,A collective list of free APIs,"14,173",Python
6,EbookFoundation / free-programming-books,📚 Freely available programming books,"208,705",Rust
7,coolsnowwolf / lede,Lean's OpenWrt source,"23,747",JavaScript
8,sensity-ai / dot,The Deepfake Offensive Toolkit,925,Nunjucks
9,sunface / rust-by-practice,"Learning Rust By Practice, narrowing the gap b...",22,JavaScript
10,Developer-Y / cs-video-courses,List of Computer Science courses with video le...,"200,334",Shell
11,pucherot / Pi.Alert,WIFI / LAN intruder detector. Check the device...,"22,998",Jupyter Notebook
12,h5bp / Front-end-Developer-Interview-Questions,A list of helpful front-end related questions ...,"239,252",TypeScript
13,yangshun / tech-interview-handbook,💯 Curated interview preparation materials for ...,"49,521",Java
14,pi-hole / pi-hole,A black hole for Internet advertisements,"22,112",Java
15,microsoft / ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...","17,613",TypeScript
16,massCodeIO / massCode,Next version of massCode. A free and open sour...,"2,489",Go
17,All-Cups / aicup22,[Forge Mod] Building Tools and Aesthetic Techn...,158,C#
18,Creators-of-Create / Create,Fig adds autocomplete to your terminal.,"4,568",Python
19,withfig / autocomplete,Hyperscale OpenShift - clusters with hosted co...,239,HTML
20,openshift / hypershift,The Token Stealer,"38,833",JavaScript

In [32]:
driver.close()

In [2]:
# 6. Scrape the details of top 100 songs on billiboard.com.Url = https:/www.billboard.com/  You have to find the following details:
#A) Song name B) Artist name C) Last week rank D) Peak rank E) Weeks on board Note: - From the home page you have to click on the charts option then hot 100-page link through code.

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="https:/www.billboard.com/" 
driver.get(url)
delay = 30  #wait till we find this xpath
WebDriverWait(driver,delay).until(EC.element_to_be_clickable((By.XPATH,"//div[@class='main-sub-menu // u-padding-tb-075@desktop u-display-none@mobile-max lrv-u-width-100p u-box-shadow-header-main lrv-u-position-relative u-z-index-middle-bottom']/nav[1]/ul/li[1]/a")))
charts = driver.find_elements_by_xpath("//div[@class='main-sub-menu // u-padding-tb-075@desktop u-display-none@mobile-max lrv-u-width-100p u-box-shadow-header-main lrv-u-position-relative u-z-index-middle-bottom']/nav[1]/ul/li[1]/a")
for i in charts:
    link = i.get_attribute('href')
    if 'charts/hot-100' in link:  #getting link of reuired page
        driver.implicitly_wait(10)
        driver.get(link)
        break
        
        
#maximize the chrome window
driver.maximize_window()

In [12]:
# Empty List
Song_name=[]
Artist_name=[]
Last_week_rank=[]
Peak_rank=[]
Weeks_board=[]

# Scrapping Data
for i in driver.find_elements_by_xpath('//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li[1]/h3'):
    Song_name.append(i.text)
for i in driver.find_elements_by_xpath('//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li[1]/span'):
    Artist_name.append(i.text)
for i in driver.find_elements_by_xpath('//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li[4]/span'):
    Last_week_rank.append(i.text)
for i in driver.find_elements_by_xpath('//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li[5]/span'):
    Peak_rank.append(i.text)
for i in driver.find_elements_by_xpath('//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li[6]/span'):
    Weeks_board.append(i.text)

#DataFrame
Songs=pd.DataFrame({'Song name':Song_name,'Artist name':Artist_name,'Last week rank':Last_week_rank,'Peak rank':Peak_rank,'Weeks board':Weeks_board})
Songs

,Song name,Artist name,Last week rank,Peak rank,Weeks board
0,As It Was,Harry Styles,1,1,14
1,About Damn Time,Lizzo,3,2,12
2,First Class,Jack Harlow,2,1,13
3,Running Up That Hill (A Deal With God),Kate Bush,6,4,26
4,Wait For U,Future Featuring Drake & Tems,4,1,10
...,...,...,...,...,...
95,Best Thing Since Backroads,Jake Owen,-,96,1
96,U-Digg,"Lil Baby, 42 Dugg & Veeze",82,52,3
97,Unstoppable,Sia,-,98,1
98,Rich Minion,Yeat,-,99,1
99,Bad Habit,Steve Lacy,-,100,1

In [13]:
driver.close()

In [42]:
# 7. Scrape the details of Data science recruiters from naukri.com.Url = https://www.naukri.com/naukri-dot-com-recruiters You have to find the following details:
#A) Name B) Designation C) Company D) Skills they hire for E) Location Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="https://www.naukri.com/naukri-dot-com-recruiters" 
driver.get(url)

#maximize the chrome window
driver.maximize_window() 

# Search 
Search=driver.find_element_by_xpath('//div[@class="sWrap lftBrd sOpen"]/div[2]/input')
Search.send_keys("Data Science")

# Click
driver.find_element_by_xpath('//button[@class="fl qsbSrch blueBtn"]').click()

In [66]:
# Empty List
Name=[]
Designation=[]
Company=[]
Skills=[]
Location=[]

#Scrapping Data
for i in driver.find_elements_by_xpath('//span[@class="fl ellipsis"]'):
    Name.append(i.text)
for i in driver.find_elements_by_xpath('//span[@class="ellipsis clr"]'):
    Designation.append(i.text)
for i in driver.find_elements_by_xpath('//p[@class="highlightable"]/a[2]'):
    Company.append(i.text)
for i in driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]'):
    Skills.append(i.text)
try:
    for i in driver.find_elements_by_xpath('//small[@class="ellipsis"]'):
        Location.append(i.text)
except:
    Location.append("no location")
    
# Creating DataFrame
Details=pd.DataFrame({'Name':Name[:48],'Designation':Designation[:48],'Company':Company[:48],'Skills':Skills[:48],'Location':Location[:48]})
Details

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Mysoru / Mysore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Hyderabad / Secunderabad
33,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
34,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Bengaluru / Bangalore
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",New Delhi
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai

In [67]:
driver.close()

In [14]:
# 8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
# You have to find the following details:A) Book name B) Author name C) Volumes sold D) Publisher E) Genre

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/" 
driver.get(url)

#maximize the chrome window
driver.maximize_window()

In [15]:
# 9. Scrape the details most watched tv series of all time from imdb.com.Url = https://www.imdb.com/list/ls095964455/You have to find the following details:
#A) Name B) Year span C) Genre D) Run time E) Ratings F) Votes

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="https://www.imdb.com/list/ls095964455/" 
driver.get(url)

#maximize the chrome window
driver.maximize_window()

In [24]:
# Empty List
Name=[]
Year_span=[] 
Genre=[] 
Run_time=[]
Ratings=[]
Votes=[]

# Scrapping Data
for i in driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a'):
    Name.append(i.text)
for i in driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/span[2]'):
    Year_span.append(i.text)
for i in driver.find_elements_by_xpath('//p[@class="text-muted text-small"]/span[5]'):
    Genre.append(i.text)
for i in driver.find_elements_by_xpath('//p[@class="text-muted text-small"]/span[3]'):
    Run_time.append(i.text)
for i in driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]/span[2]'):
    Ratings.append(i.text)
for i in driver.find_elements_by_xpath('//div[@class="lister-item-content"]/p[4]/span[2]'):
    Votes.append(i.text)

# DataFrame
lists=pd.DataFrame({'Name':Name,'Year span':Year_span,'Genre':Genre,'Run time':Run_time,'Ratings':Ratings,'Votes':Votes})
lists

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,008,042"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,086,042"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"954,608"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"285,382"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"245,038"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,075"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,875"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"192,132"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,568"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"231,004"

In [25]:
driver.close()

In [27]:
# 10. Details of Datasets from UCI machine learning repositories.Url = https://archive.ics.uci.edu/ You have to find the following details:
# A) Dataset name B) Data type C) Task D) Attribute type E) No of instances F) No of attribute G) Year Note: - from the home page you have to go to the ShowAllDataset page through code

#connect to web driver
chrome_options=Options()
chrome_options.add_argument("disable--infobars")
chrome_options.add_argument("--incognito")
driver=webdriver.Chrome(r"C:\Users\shaha\Desktop\My Course\DataTrained\chromedriver_win32\chromedriver.exe", options=chrome_options)

# webpage by url :
url="https://archive.ics.uci.edu/" 
driver.get(url)

#maximize the chrome window
driver.maximize_window() 

# Getting all_data_set
driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a').click()

In [32]:
url = driver.current_url
url

'https://archive.ics.uci.edu/ml/datasets.php'

In [40]:
page=requests.get(url) #send get request to the webpage server to get the source code of the page
print(page)

print('-------------------------------')

bs=BeautifulSoup(page.content)
#getting the table by using pandas readhtml method
Table=bs.find_all('table')

df = pd.read_html(str(Table))[5]
df

<Response [200]>
-------------------------------

,0,1,2,3,4,5,6
0,Name,Data Types,Default Task,Attribute Types,# Instances,# Attributes,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,NaN
4,Anonymous Microsoft Web Data,NaN,Recommender-Systems,Categorical,37711,294,1998
...,...,...,...,...,...,...,...
182,Acute Inflammations,Multivariate,Classification,"Categorical, Integer",120,6,2009
183,Wine Quality,Multivariate,"Classification, Regression",Real,4898,12,2009
184,URL Reputation,"Multivariate, Time-Series",Classification,"Integer, Real",2396130,3231961,2009
185,p53 Mutants,Multivariate,Classification,Real,16772,5409,2010
186,Parkinsons Telemonitoring,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
driver.close()